"""empty message

Revision ID: 801f41743abb
Revises: 4a7acb949aa1
Create Date: 2019-06-23 04:23:25.050005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801f41743abb'
down_revision = '4a7acb949aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('feedback_timestamp', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('category', sa.String(length=16), nullable=True))
    op.add_column('message', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'rate')
    op.drop_column('message', 'category')
    op.drop_column('chat', 'feedback_timestamp')
    # ### end Alembic commands ###
