"""empty message

Revision ID: b9380f334131
Revises: 801f41743abb
Create Date: 2019-06-23 07:19:47.406773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9380f334131'
down_revision = '801f41743abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('messages_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'messages_count')
    # ### end Alembic commands ###
